CREATE DATABASE SmartLybrary

USE SmartLybrary

CREATE SCHEMA Book
GO

CREATE SCHEMA Person
GO

CREATE SCHEMA Sales
GO

CREATE TABLE Person.Country (
	CountryID UNIQUEIDENTIFIER PRIMARY KEY,
	CountryName NVARCHAR (50) NOT NULL,
	Iso NVARCHAR (3) NOT NULL,
	IsActive BIT DEFAULT (1)
)
GO

CREATE TABLE Person.Person (
	PersonID UNIQUEIDENTIFIER PRIMARY KEY,
	FirstName1 NVARCHAR (50) NOT NULL,
	FirstName2 NVARCHAR (50) NOT NULL,
	LastName1 NVARCHAR (50) NOT NULL,
	LastName2 NVARCHAR (50) NOT NULL,
	IsActive BIT DEFAULT (1)
)
GO

SELECT * FROM Person.Person
GO

CREATE TABLE Person.Autor (
	AutorID UNIQUEIDENTIFIER PRIMARY KEY,
	CountryID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Person.Country (CountryID),
	PersonID UNIQUEIDENTIFIER UNIQUE FOREIGN KEY REFERENCES Person.Person (PersonID),
	CreationDate DATE DEFAULT GETDATE() NOT NULL,
	IsActive BIT DEFAULT (1)
)
GO

SELECT * FROM Person.Autor
GO

CREATE TABLE Person.Cliente(
	ClienteID UNIQUEIDENTIFIER PRIMARY KEY,
	PersonID UNIQUEIDENTIFIER UNIQUE FOREIGN KEY REFERENCES Person.Person (PersonID),
	CountryID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Person.Country (CountryID),
	IsActive BIT DEFAULT (1)
)
GO

CREATE TABLE Sales.TipoDocumento(
	TipoDocumentID UNIQUEIDENTIFIER PRIMARY KEY,
	DocumentName NVARCHAR (50) NOT NULL,
	IsActive BIT DEFAULT(1)
)
GO

CREATE TABLE Sales.Factura(
	FacturaID UNIQUEIDENTIFIER PRIMARY KEY,
	ClienteID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Person.Cliente(ClienteID),
	TipoDocumentID UNIQUEIDENTIFIER UNIQUE FOREIGN KEY REFERENCES Sales.TipoDocumento (TipoDocumentID),
	FechaCreacion DATE DEFAULT GETDATE(),
	IsActive BIT DEFAULT(1)
)
GO

CREATE TABLE Book.Gender(
	GenderID UNIQUEIDENTIFIER PRIMARY KEY,
	GenderName NVARCHAR (50) NOT NULL,
	IsActive BIT DEFAULT(1)
)
GO

CREATE TABLE Book.Editorial(
	EditorialID UNIQUEIDENTIFIER PRIMARY KEY,
	EditorialName NVARCHAR (50) NOT NULL,
	CountryID UNIQUEIDENTIFIER UNIQUE FOREIGN KEY REFERENCES Person.Country (CountryID),
	IsActive BIT DEFAULT(1)
)
GO

CREATE TABLE Book.Books(
	BookID UNIQUEIDENTIFIER PRIMARY KEY,
	GenderID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Book.Gender (GenderID),
	AutorID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Person.Autor(AutorID),
	EditorialID UNIQUEIDENTIFIER UNIQUE FOREIGN KEY REFERENCES Book.Editorial(EditorialID),
	IsActive BIT DEFAULT(1),
	BookImage VARBINARY (MAX)
)
GO

CREATE TABLE Sales.InvoiceDetails(
	InvoiceDetailsID UNIQUEIDENTIFIER PRIMARY KEY,
	BookID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Book.Books(BookID),
	FacturaID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Sales.Factura(FacturaID),
	Price DECIMAL NOT NULL,
	Cuantity INT NOT NULL,
	Iva DECIMAL NOT NULL,
	Total DECIMAL NOT NULL
)
GO



